baseURL = 'https://hexpysya.github.io/bubka/'
languageCode = 'en-us'
title = 'bubka hacks stuff'
theme = "blowfish"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = 'github-dark'
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
[[menus.main]]
  name = "investigations"
  pageRef = "investigations"  
  weight = 10

[[menus.main]]
  name = "blue team"
  pageRef = "blue_team"        
  weight = 20


[params]
colorScheme = "github"
# avocado, fire, ocean, forest, princess, neon, bloody, terminal, marvel, noir, autumn, congo, slate, github, and one-light
defaultAppearance = "light" # valid options: light or dark
defaultBackgroundImage = ".jpg"
highlightCurrentMenuArea = false
smartTOC = true
favicon = "favicon.ico"
description = "Writeups on malware analysis, reverse engineering and DFIR."
[params.header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[params.footer]
  showMenu = true
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[params.homepage]
  layout = "background" # valid options: page, profile, hero, card, background, custom
  homepage = "IMAGE.jpg"
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "investigations"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background
  disableHeroImageFilter = false # only used when layout equals hero

[params.article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  # showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = false
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  # showRelatedContent = false
  # relatedContentLimit = 3
  showTaxonomies = true # use showTaxonomies OR showCategoryOnly, not both
  showCategoryOnly = false # use showTaxonomies OR showCategoryOnly, not both
  showAuthorsBadges = true
  showWordCount = false
  # sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram", "line"]
  showZenMode = false
  # externalLinkForceNewTab = false # disable to allow external links in the same tab (defaults to true)

[params.list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false   # ось це зміни
  cardViewScreenWidth = false
  constrainItemsWidth = false

[params.taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false


[params.author]
  name = "Bubka" 
  headline = "Malware Analysis | Reverse Engineering | Digital Forensics and Incident Response"
  image = "avatar.JPG" 
  bio = "Writeups on malware analysis, reverse engineering and DFIR."

[imaging]
  resampleFilter = "Lanczos"
  quality = 100              
  hint = "photo"

[taxonomies]
  tag = "tags"
  category = "categories"